name: Build Web
description: Builds the Web codebase with quality gates

inputs:
  working_directory:
    description: The working directory where the code will be built.
    required: true
  node_version:
    description: The node version that will be used.
    required: true

runs:
  using: composite

  steps:
    - name: Use Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}

    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: Lint check
      run: npm run lint
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      continue-on-error: false

    - name: Prettier format check
      run: |
        if [ -f "package.json" ] && grep -q "prettier:check" package.json; then
          npm run prettier:check
        else
          npx prettier --check "src/**/*.{vue,ts,js}"
        fi
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: Build
      run: npm run build
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: Test
      run: npm run test
      shell: bash
      working-directory: ${{ inputs.working_directory }}

    - name: Spell check
      uses: streetsidesoftware/cspell-action@v6
      with:
        files: |
          web/src/**/*.{vue,ts,js}
        config: .github/cspell.json
        strict: true
        incremental_files_only: false
